#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import sys
import subprocess

# ===================== 全局配置 =====================
TOTAL_API_RUNTIME = 347
TOTAL_API_CUBLAS = 326
TOTAL_API_CUFFT = 52
TOTAL_API_NCCL = 19
RUNTIME_DIR = "build/cuda_test"
CUBLAS_DIR  = "build/cublas_test"
CUFFT_DIR   = "build/cufft_test"
NCCL_DIR    = "build/nccl_test"

# ===================== RUNTIME 全部用例 =====================
RUNTIME_TESTS = [
    "test_cudaArrayGetInfo",
    "test_cudaArrayGetMemoryRequirements",
    "test_cudaBindSurfaceToArray",
    "test_cudaBindTexture",
    "test_cudaBindTexture2D",
    "test_cudaBindTextureToArray",
    "test_cudaBindTextureToMipmappedArray",
    "test_cudaChooseDevice",
    "test_cudaCreateChannelDesc",
    "test_cudaCreateSurfaceObject",
    "test_cudaCreateTextureObject",
    "test_cudaDestroyExternalMemory",
    "test_cudaDestroyExternalSemaphore",
    "test_cudaDestroySurfaceObject",
    "test_cudaDestroyTextureObject",
    "test_cudaDeviceCanAccessPeer",
    "test_cudaDeviceDisablePeerAccess",
    "test_cudaDeviceEnablePeerAccess",
    "test_cudaDeviceGetAttribute",
    "test_cudaDeviceGetByPCIBusId",
    "test_cudaDeviceGetCacheConfig",
    "test_cudaDeviceGetDefaultMemPool",
    "test_cudaDeviceGetGraphMemAttribute",
    "test_cudaDeviceGetLimit",
    "test_cudaDeviceGetMemPool",
    "test_cudaDeviceGetP2PAttribute",
    "test_cudaDeviceGetPCIBusId",
    "test_cudaDeviceGetSharedMemConfig",
    "test_cudaDeviceGetStreamPriorityRange",
    "test_cudaDeviceGraphMemTrim",
    "test_cudaDeviceReset",
    "test_cudaDeviceSetCacheConfig",
    "test_cudaDeviceSetGraphMemAttribute",
    "test_cudaDeviceSetLimit",
    "test_cudaDeviceSetMemPool",
    "test_cudaDeviceSetSharedMemConfig",
    "test_cudaDeviceSynchronize",
    "test_cudaDriverGetVersion",
    "test_cudaEventCreate",
    "test_cudaEventCreateWithFlags",
    "test_cudaEventDestroy",
    "test_cudaEventElapsedTime",
    "test_cudaEventQuery",
    "test_cudaEventRecord",
    "test_cudaEventRecord_ptsz",
    "test_cudaEventRecordWithFlags",
    "test_cudaEventRecordWithFlags_ptsz",
    "test_cudaEventSynchronize",
    "test_cudaExternalMemoryGetMappedBuffer",
    "test_cudaExternalMemoryGetMappedMipmappedArray",
    "test_cudaFree",
    "test_cudaFreeArray",
    "test_cudaFreeAsync",
    "test_cudaFreeAsync_ptsz",
    "test_cudaFreeHost",
    "test_cudaFreeMipmappedArray",
    "test_cudaFuncGetAttributes",
    "test_cudaFuncSetAttribute",
    "test_cudaFuncSetCacheConfig",
    "test_cudaFuncSetSharedMemConfig",
    "test_cudaGetChannelDesc",
    "test_cudaGetDevice",
    "test_cudaGetDeviceCount",
    "test_cudaGetDeviceFlags",
    "test_cudaGetDeviceProperties",
    "test_cudaGetDriverEntryPoint",
    "test_cudaGetDriverEntryPoint_ptsz",
    "test_cudaGetErrorName",
    "test_cudaGetErrorString",
    "test_cudaGetFuncBySymbol",
    "test_cudaGetLastError",
    "test_cudaGetMipmappedArrayLevel",
    "test_cudaGetSurfaceObjectResourceDesc",
    "test_cudaGetSurfaceReference",
    "test_cudaGetSymbolAddress",
    "test_cudaGetSymbolSize",
    "test_cudaGetTextureAlignmentOffset",
    "test_cudaGetTextureObjectResourceDesc",
    "test_cudaGetTextureObjectResourceViewDesc",
    "test_cudaGetTextureObjectTextureDesc",
    "test_cudaGetTextureObjectTextureDesc_v2",
    "test_cudaGetTextureReference",
    "test_cudaGLGetDevices",
    "test_cudaGraphAddChildGraphNode",
    "test_cudaGraphAddDependencies",
    "test_cudaGraphAddEmptyNode",
    "test_cudaGraphAddEventRecordNode",
    "test_cudaGraphAddEventWaitNode",
    "test_cudaGraphAddExternalSemaphoresSignalNode",
    "test_cudaGraphAddExternalSemaphoresWaitNode",
    "test_cudaGraphAddHostNode",
    "test_cudaGraphAddKernelNode",
    "test_cudaGraphAddMemAllocNode",
    "test_cudaGraphAddMemcpyNode",
    "test_cudaGraphAddMemcpyNode1D",
    "test_cudaGraphAddMemcpyNodeFromSymbol",
    "test_cudaGraphAddMemcpyNodeToSymbol",
    "test_cudaGraphAddMemFreeNode",
    "test_cudaGraphAddMemsetNode",
    "test_cudaGraphChildGraphNodeGetGraph",
    "test_cudaGraphClone",
    "test_cudaGraphCreate",
    "test_cudaGraphDebugDotPrint",
    "test_cudaGraphDestroy",
    "test_cudaGraphDestroyNode",
    "test_cudaGraphEventRecordNodeGetEvent",
    "test_cudaGraphEventRecordNodeSetEvent",
    "test_cudaGraphEventWaitNodeGetEvent",
    "test_cudaGraphEventWaitNodeSetEvent",
    "test_cudaGraphExecChildGraphNodeSetParams",
    "test_cudaGraphExecDestroy",
    "test_cudaGraphExecEventRecordNodeSetEvent",
    "test_cudaGraphExecEventWaitNodeSetEvent",
    "test_cudaGraphExecExternalSemaphoresSignalNodeSetParams",
    "test_cudaGraphExecExternalSemaphoresWaitNodeSetParams",
    "test_cudaGraphExecHostNodeSetParams",
    "test_cudaGraphExecKernelNodeSetParams",
    "test_cudaGraphExecMemcpyNodeSetParams",
    "test_cudaGraphExecMemcpyNodeSetParams1D",
    "test_cudaGraphExecMemcpyNodeSetParamsToSymbol",
    "test_cudaGraphExecMemcpyNodeSetParamsFromSymbol",
    "test_cudaGraphExecMemsetNodeSetParams",
    "test_cudaGraphExecUpdate",
    "test_cudaGraphExternalSemaphoresSignalNodeGetParams",
    "test_cudaGraphExternalSemaphoresSignalNodeSetParams",
    "test_cudaGraphExternalSemaphoresWaitNodeGetParams",
    "test_cudaGraphExternalSemaphoresWaitNodeSetParams",
    "test_cudaGraphGetEdges",
    "test_cudaGraphGetNodes",
    "test_cudaGraphGetRootNodes",
    "test_cudaGraphHostNodeGetParams",
    "test_cudaGraphHostNodeSetParams",
    "test_cudaGraphicsGLRegisterBuffer",
    "test_cudaGraphicsGLRegisterImage",
    "test_cudaGraphicsMapResources",
    "test_cudaGraphicsResourceGetMappedPointer",
    "test_cudaGraphicsSubResourceGetMappedArray",
    "test_cudaGraphicsUnregisterResource",
    "test_cudaGraphInstantiate",
    "test_cudaGraphInstantiateWithFlags",
    "test_cudaGraphKernelNodeCopyAttributes",
    "test_cudaGraphKernelNodeGetAttribute",
    "test_cudaGraphKernelNodeGetParams",
    "test_cudaGraphKernelNodeSetAttribute",
    "test_cudaGraphKernelNodeSetParams",
    "test_cudaGraphLaunch",
    "test_cudaGraphLaunch_ptsz",
    "test_cudaGraphMemAllocNodeGetParams",
    "test_cudaGraphMemcpyNodeGetParams",
    "test_cudaGraphMemcpyNodeSetParams",
    "test_cudaGraphMemcpyNodeSetParams1D",
    "test_cudaGraphMemcpyNodeSetParamsFromSymbol",
    "test_cudaGraphMemcpyNodeSetParamsToSymbol",
    "test_cudaGraphMemFreeNodeGetParams",
    "test_cudaGraphMemsetNodeGetParams",
    "test_cudaGraphMemsetNodeSetParams",
    "test_cudaGraphNodeFindInClone",
    "test_cudaGraphNodeGetDependencies",
    "test_cudaGraphNodeGetDependentNodes",
    "test_cudaGraphNodeGetEnabled",
    "test_cudaGraphNodeGetType",
    "test_cudaGraphNodeSetEnabled",
    "test_cudaGraphReleaseUserObject",
    "test_cudaGraphRemoveDependencies",
    "test_cudaGraphRetainUserObject",
    "test_cudaGraphUpload",
    "test_cudaGraphUpload_ptsz",
    "test_cudaHostAlloc",
    "test_cudaHostGetDevicePointer",
    "test_cudaHostGetFlags",
    "test_cudaHostRegister",
    "test_cudaHostUnregister",
    "test_cudaImportExternalMemory",
    "test_cudaImportExternalSemaphore",
    "test_cudaIpcCloseMemHandle",
    "test_cudaIpcGetEventHandle",
    "test_cudaIpcGetMemHandle",
    "test_cudaIpcOpenEventHandle",
    "test_cudaIpcOpenMemHandle",
    "test_cudaLaunchCooperativeKernel",
    "test_cudaLaunchCooperativeKernelMultiDevice",
    "test_cudaLaunchCooperativeKernel_ptsz",
    "test_cudaLaunchHostFunc",
    "test_cudaLaunchHostFunc_ptsz",
    "test_cudaLaunchKernel",
    "test_cudaLaunchKernelExC",
    "test_cudaLaunchKernelExC_ptsz",
    "test_cudaLaunchKernel_ptsz",
    "test_cudaMalloc",
    "test_cudaMalloc3D",
    "test_cudaMalloc3DArray",
    "test_cudaMallocArray",
    "test_cudaMallocAsync",
    "test_cudaMallocAsync_ptsz",
    "test_cudaMallocFromPoolAsync",
    "test_cudaMallocFromPoolAsync_ptsz",
    "test_cudaMallocHost",
    "test_cudaMallocManaged",
    "test_cudaMallocMipmappedArray",
    "test_cudaMallocPitch",
    "test_cudaMemAdvise",
    "test_cudaMemcpy",
    "test_cudaMemcpy2D",
    "test_cudaMemcpy2DArrayToArray",
    "test_cudaMemcpy2DArrayToArray_ptds",
    "test_cudaMemcpy2DAsync",
    "test_cudaMemcpy2DAsync_ptsz",
    "test_cudaMemcpy2DFromArray",
    "test_cudaMemcpy2DFromArrayAsync",
    "test_cudaMemcpy2DFromArrayAsync_ptsz",
    "test_cudaMemcpy2DFromArray_ptds",
    "test_cudaMemcpy2D_ptds",
    "test_cudaMemcpy2DToArray",
    "test_cudaMemcpy2DToArrayAsync",
    "test_cudaMemcpy2DToArrayAsync_ptsz",
    "test_cudaMemcpy2DToArray_ptds",
    "test_cudaMemcpy3D",
    "test_cudaMemcpy3DAsync",
    "test_cudaMemcpy3DAsync_ptsz",
    "test_cudaMemcpy3DPeer",
    "test_cudaMemcpy3DPeerAsync",
    "test_cudaMemcpy3DPeerAsync_ptsz",
    "test_cudaMemcpy3DPeer_ptds",
    "test_cudaMemcpy3D_ptds",
    "test_cudaMemcpyArrayToArray",
    "test_cudaMemcpyArrayToArray_ptds",
    "test_cudaMemcpyAsync",
    "test_cudaMemcpyAsync_ptsz",
    "test_cudaMemcpyFromArray",
    "test_cudaMemcpyFromArrayAsync",
    "test_cudaMemcpyFromArrayAsync_ptsz",
    "test_cudaMemcpyFromArray_ptds",
    "test_cudaMemcpyFromSymbol",
    "test_cudaMemcpyFromSymbol_ptds",
    "test_cudaMemcpyFromSymbolAsync",
    "test_cudaMemcpyFromSymbolAsync_ptsz",
    "test_cudaMemcpyPeer",
    "test_cudaMemcpyPeerAsync",
    "test_cudaMemcpy_ptds",
    "test_cudaMemcpyToArray",
    "test_cudaMemcpyToArrayAsync",
    "test_cudaMemcpyToArrayAsync_ptsz",
    "test_cudaMemcpyToArray_ptds",
    "test_cudaMemcpyToSymbol",
    "test_cudaMemcpyToSymbol_ptds",
    "test_cudaMemcpyToSymbolAsync",
    "test_cudaMemcpyToSymbolAsync_ptsz",
    "test_cudaMemGetInfo",
    "test_cudaMemPoolCreate",
    "test_cudaMemPoolDestroy",
    "test_cudaMemPoolExportPointer",
    "test_cudaMemPoolExportToShareableHandle",
    "test_cudaMemPoolGetAccess",
    "test_cudaMemPoolGetAttribute",
    "test_cudaMemPoolImportFromShareableHandle",
    "test_cudaMemPoolImportPointer",
    "test_cudaMemPoolSetAccess",
    "test_cudaMemPoolSetAttribute",
    "test_cudaMemPoolTrimTo",
    "test_cudaMemPrefetchAsync",
    "test_cudaMemPrefetchAsync_ptsz",
    "test_cudaMemRangeGetAttribute",
    "test_cudaMemRangeGetAttributes",
    "test_cudaMemset",
    "test_cudaMemset2D",
    "test_cudaMemset2DAsync",
    "test_cudaMemset2DAsync_ptsz",
    "test_cudaMemset2D_ptds",
    "test_cudaMemset3D",
    "test_cudaMemset3DAsync",
    "test_cudaMemset3DAsync_ptsz",
    "test_cudaMemset3D_ptds",
    "test_cudaMemsetAsync",
    "test_cudaMemsetAsync_ptsz",
    "test_cudaMemset_ptds",
    "test_cudaMipmappedArrayGetMemoryRequirements",
    "test_cudaOccupancyMaxActiveBlocksPerMultiprocessor",
    "test_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags",
    "test_cudaPeekAtLastError",
    "test_cudaPointerGetAttributes",
    "test___cudaPopCallConfiguration",
    "test_cudaProfilerStart",
    "test_cudaProfilerStop",
    "test___cudaPushCallConfiguration",
    "test___cudaRegisterFatBinary",
    "test___cudaRegisterFunction",
    "test___cudaRegisterManagedVar",
    "test___cudaRegisterSurface",
    "test___cudaRegisterTexture",
    "test___cudaRegisterVar",
    "test_cudaRuntimeGetVersion",
    "test_cudaSetDevice",
    "test_cudaSetDeviceFlags",
    "test_cudaSetValidDevices",
    "test_cudaSignalExternalSemaphoresAsync",
    "test_cudaSignalExternalSemaphoresAsync_v2",
    "test_cudaSignalExternalSemaphoresAsync_v2_ptsz",
    "test_cudaStreamAddCallback",
    "test_cudaStreamAddCallback_ptsz",
    "test_cudaStreamAttachMemAsync",
    "test_cudaStreamAttachMemAsync_ptsz",
    "test_cudaStreamBeginCapture",
    "test_cudaStreamBeginCapture_ptsz",
    "test_cudaStreamCopyAttributes",
    "test_cudaStreamCopyAttributes_ptsz",
    "test_cudaStreamCreate",
    "test_cudaStreamCreateWithFlags",
    "test_cudaStreamCreateWithPriority",
    "test_cudaStreamDestroy",
    "test_cudaStreamEndCapture",
    "test_cudaStreamEndCapture_ptsz",
    "test_cudaStreamGetAttribute",
    "test_cudaStreamGetAttribute_ptsz",
    "test_cudaStreamGetCaptureInfo",
    "test_cudaStreamGetCaptureInfo_ptsz",
    "test_cudaStreamGetCaptureInfo_v2",
    "test_cudaStreamGetCaptureInfo_v2_ptsz",
    "test_cudaStreamGetFlags",
    "test_cudaStreamGetFlags_ptsz",
    "test_cudaStreamGetPriority",
    "test_cudaStreamGetPriority_ptsz",
    "test_cudaStreamIsCapturing",
    "test_cudaStreamIsCapturing_ptsz",
    "test_cudaStreamQuery",
    "test_cudaStreamQuery_ptsz",
    "test_cudaStreamSetAttribute",
    "test_cudaStreamSetAttribute_ptsz",
    "test_cudaStreamSynchronize",
    "test_cudaStreamSynchronize_ptsz",
    "test_cudaStreamUpdateCaptureDependencies",
    "test_cudaStreamWaitEvent",
    "test_cudaStreamWaitEvent_ptsz",
    "test_cudaThreadExchangeStreamCaptureMode",
    "test_cudaThreadExit",
    "test_cudaThreadGetCacheConfig",
    "test_cudaThreadGetLimit",
    "test_cudaThreadSetCacheConfig",
    "test_cudaThreadSetLimit",
    "test_cudaThreadSynchronize",
    "test_cudaUnbindTexture",
    "test___cudaUnregisterFatBinary",
    "test_cudaUserObjectCreate",
    "test_cudaUserObjectRelease",
    "test_cudaUserObjectRetain",
    "test_cudaWaitExternalSemaphoresAsync",
    "test_cudaWaitExternalSemaphoresAsync_v2",
    "test_cudaWaitExternalSemaphoresAsync_v2_ptsz",
]

# ===================== CUBLAS 全部用例 =====================
CUBLAS_TESTS = [
    "test_cublasAxpyEx",
    "test_cublasCaxpy_v2",
    "test_cublasCcopy_v2",
    "test_cublasCdgmm",
    "test_cublasCdotc_v2",
    "test_cublasCdotu_v2",
    "test_cublasCgbmv_v2",
    "test_cublasCgeam",
    "test_cublasCgelsBatched",
    "test_cublasCgemm3m",
    "test_cublasCgemm3mStridedBatched",
    "test_cublasCgemmBatched",
    "test_cublasCgemmEx",
    "test_cublasCgemmStridedBatched",
    "test_cublasCgemm_v2",
    "test_cublasCgemvBatched",
    "test_cublasCgemvStridedBatched",
    "test_cublasCgemv_v2",
    "test_cublasCgeqrfBatched",
    "test_cublasCgerc_v2",
    "test_cublasCgeru_v2",
    "test_cublasCgetrfBatched",
    "test_cublasCgetriBatched",
    "test_cublasCgetrsBatched",
    "test_cublasChbmv_v2",
    "test_cublasChemm_v2",
    "test_cublasChemv_v2",
    "test_cublasCher2k_v2",
    "test_cublasCher2_v2",
    "test_cublasCherk3mEx",
    "test_cublasCherkEx",
    "test_cublasCherk_v2",
    "test_cublasCherkx",
    "test_cublasCher_v2",
    "test_cublasChpmv_v2",
    "test_cublasChpr2_v2",
    "test_cublasChpr_v2",
    "test_cublasCmatinvBatched",
    "test_cublasCreate_v2",
    "test_cublasCrotg_v2",
    "test_cublasCrot_v2",
    "test_cublasCscal_v2",
    "test_cublasCsrot_v2",
    "test_cublasCsscal_v2",
    "test_cublasCswap_v2",
    "test_cublasCsymm_v2",
    "test_cublasCsymv_v2",
    "test_cublasCsyr2k_v2",
    "test_cublasCsyr2_v2",
    "test_cublasCsyrk3mEx",
    "test_cublasCsyrkEx",
    "test_cublasCsyrk_v2",
    "test_cublasCsyrkx",
    "test_cublasCsyr_v2",
    "test_cublasCtbmv_v2",
    "test_cublasCtbsv_v2",
    "test_cublasCtpmv_v2",
    "test_cublasCtpsv_v2",
    "test_cublasCtpttr",
    "test_cublasCtrmm_v2",
    "test_cublasCtrmv_v2",
    "test_cublasCtrsmBatched",
    "test_cublasCtrsm_v2",
    "test_cublasCtrsv_v2",
    "test_cublasCtrttp",
    "test_cublasDasum_v2",
    "test_cublasDaxpy_v2",
    "test_cublasDcopy_v2",
    "test_cublasDdgmm",
    "test_cublasDdot_v2",
    "test_cublasDestroy_v2",
    "test_cublasDgbmv_v2",
    "test_cublasDgeam",
    "test_cublasDgelsBatched",
    "test_cublasDgemmBatched",
    "test_cublasDgemmStridedBatched",
    "test_cublasDgemm_v2",
    "test_cublasDgemvBatched",
    "test_cublasDgemvStridedBatched",
    "test_cublasDgemv_v2",
    "test_cublasDgeqrfBatched",
    "test_cublasDger_v2",
    "test_cublasDgetrfBatched",
    "test_cublasDgetriBatched",
    "test_cublasDgetrsBatched",
    "test_cublasDmatinvBatched",
    "test_cublasDnrm2_v2",
    "test_cublasDotcEx",
    "test_cublasDotEx",
    "test_cublasDrotg_v2",
    "test_cublasDrotmg_v2",
    "test_cublasDrotm_v2",
    "test_cublasDrot_v2",
    "test_cublasDsbmv_v2",
    "test_cublasDscal_v2",
    "test_cublasDspmv_v2",
    "test_cublasDspr2_v2",
    "test_cublasDspr_v2",
    "test_cublasDswap_v2",
    "test_cublasDsymm_v2",
    "test_cublasDsymv_v2",
    "test_cublasDsyr2k_v2",
    "test_cublasDsyr2_v2",
    "test_cublasDsyrk_v2",
    "test_cublasDsyrkx",
    "test_cublasDsyr_v2",
    "test_cublasDtbmv_v2",
    "test_cublasDtbsv_v2",
    "test_cublasDtpmv_v2",
    "test_cublasDtpsv_v2",
    "test_cublasDtpttr",
    "test_cublasDtrmm_v2",
    "test_cublasDtrmv_v2",
    "test_cublasDtrsmBatched",
    "test_cublasDtrsm_v2",
    "test_cublasDtrsv_v2",
    "test_cublasDtrttp",
    "test_cublasDzasum_v2",
    "test_cublasDznrm2_v2",
    "test_cublasGemmBatchedEx",
    "test_cublasGemmEx",
    "test_cublasGemmStridedBatchedEx",
    "test_cublasGetAtomicsMode",
    "test_cublasGetCudartVersion",
    "test_cublasGetMathMode",
    "test_cublasGetMatrix",
    "test_cublasGetMatrixAsync",
    "test_cublasGetPointerMode_v2",
    "test_cublasGetProperty",
    "test_cublasGetStatusName",
    "test_cublasGetStatusString",
    "test_cublasGetStream_v2",
    "test_cublasGetVector",
    "test_cublasGetVectorAsync",
    "test_cublasGetVersion_v2",
    "test_cublasHgemm",
    "test_cublasHgemmBatched",
    "test_cublasHgemmStridedBatched",
    "test_cublasHSHgemvBatched",
    "test_cublasHSHgemvStridedBatched",
    "test_cublasHSSgemvBatched",
    "test_cublasHSSgemvStridedBatched",
    "test_cublasIcamax_v2",
    "test_cublasIcamin_v2",
    "test_cublasIdamax_v2",
    "test_cublasIdamin_v2",
    "test_cublasIsamax_v2",
    "test_cublasIsamin_v2",
    "test_cublasIzamax_v2",
    "test_cublasIzamin_v2",
    "test_cublasNrm2Ex",
    "test_cublasRotEx",
    "test_cublasSasum_v2",
    "test_cublasSaxpy_v2",
    "test_cublasScalEx",
    "test_cublasScasum_v2",
    "test_cublasScnrm2_v2",
    "test_cublasScopy_v2",
    "test_cublasSdgmm",
    "test_cublasSdot_v2",
    "test_cublasSetAtomicsMode",
    "test_cublasSetMathMode",
    "test_cublasSetMatrix",
    "test_cublasSetMatrixAsync",
    "test_cublasSetPointerMode_v2",
    "test_cublasSetStream_v2",
    "test_cublasSetVector",
    "test_cublasSetVectorAsync",
    "test_cublasSetWorkspace_v2",
    "test_cublasSgbmv_v2",
    "test_cublasSgeam",
    "test_cublasSgelsBatched",
    "test_cublasSgemmBatched",
    "test_cublasSgemmEx",
    "test_cublasSgemmStridedBatched",
    "test_cublasSgemm_v2",
    "test_cublasSgemvBatched",
    "test_cublasSgemvStridedBatched",
    "test_cublasSgemv_v2",
    "test_cublasSgeqrfBatched",
    "test_cublasSger_v2",
    "test_cublasSgetrfBatched",
    "test_cublasSgetriBatched",
    "test_cublasSgetrsBatched",
    "test_cublasSmatinvBatched",
    "test_cublasSnrm2_v2",
    "test_cublasSrotg_v2",
    "test_cublasSrotmg_v2",
    "test_cublasSrotm_v2",
    "test_cublasSrot_v2",
    "test_cublasSsbmv_v2",
    "test_cublasSscal_v2",
    "test_cublasSspmv_v2",
    "test_cublasSspr2_v2",
    "test_cublasSspr_v2",
    "test_cublasSswap_v2",
    "test_cublasSsymm_v2",
    "test_cublasSsymv_v2",
    "test_cublasSsyr2k_v2",
    "test_cublasSsyr2_v2",
    "test_cublasSsyrk_v2",
    "test_cublasSsyrkx",
    "test_cublasSsyr_v2",
    "test_cublasStbmv_v2",
    "test_cublasStbsv_v2",
    "test_cublasStpmv_v2",
    "test_cublasStpsv_v2",
    "test_cublasStpttr",
    "test_cublasStrmm_v2",
    "test_cublasStrmv_v2",
    "test_cublasStrsmBatched",
    "test_cublasStrsm_v2",
    "test_cublasStrsv_v2",
    "test_cublasStrttp",
    "test_cublasTSSgemvBatched",
    "test_cublasTSSgemvStridedBatched",
    "test_cublasTSTgemvBatched",
    "test_cublasTSTgemvStridedBatched",
    "test_cublasXtCgemm",
    "test_cublasXtChemm",
    "test_cublasXtCher2k",
    "test_cublasXtCherk",
    "test_cublasXtCherkx",
    "test_cublasXtCreate",
    "test_cublasXtCspmm",
    "test_cublasXtCsymm",
    "test_cublasXtCsyr2k",
    "test_cublasXtCsyrk",
    "test_cublasXtCsyrkx",
    "test_cublasXtCtrmm",
    "test_cublasXtCtrsm",
    "test_cublasXtDestroy",
    "test_cublasXtDeviceSelect",
    "test_cublasXtDgemm",
    "test_cublasXtDspmm",
    "test_cublasXtDsymm",
    "test_cublasXtDsyr2k",
    "test_cublasXtDsyrk",
    "test_cublasXtDsyrkx",
    "test_cublasXtDtrmm",
    "test_cublasXtDtrsm",
    "test_cublasXtGetBlockDim",
    "test_cublasXtGetNumBoards",
    "test_cublasXtGetPinningMemMode",
    "test_cublasXtMaxBoards",
    "test_cublasXtSetBlockDim",
    "test_cublasXtSetCpuRatio",
    "test_cublasXtSetCpuRoutine",
    "test_cublasXtSetPinningMemMode",
    "test_cublasXtSgemm",
    "test_cublasXtSspmm",
    "test_cublasXtSsymm",
    "test_cublasXtSsyr2k",
    "test_cublasXtSsyrk",
    "test_cublasXtSsyrkx",
    "test_cublasXtStrmm",
    "test_cublasXtStrsm",
    "test_cublasXtZgemm",
    "test_cublasXtZhemm",
    "test_cublasXtZher2k",
    "test_cublasXtZherk",
    "test_cublasXtZherkx",
    "test_cublasXtZspmm",
    "test_cublasXtZsymm",
    "test_cublasXtZsyr2k",
    "test_cublasXtZsyrk",
    "test_cublasXtZsyrkx",
    "test_cublasXtZtrmm",
    "test_cublasXtZtrsm",
    "test_cublasZaxpy_v2",
    "test_cublasZcopy_v2",
    "test_cublasZdgmm",
    "test_cublasZdotc_v2",
    "test_cublasZdotu_v2",
    "test_cublasZdrot_v2",
    "test_cublasZdscal_v2",
    "test_cublasZgbmv_v2",
    "test_cublasZgeam",
    "test_cublasZgelsBatched",
    "test_cublasZgemm3m",
    "test_cublasZgemmBatched",
    "test_cublasZgemmStridedBatched",
    "test_cublasZgemm_v2",
    "test_cublasZgemvBatched",
    "test_cublasZgemvStridedBatched",
    "test_cublasZgemv_v2",
    "test_cublasZgeqrfBatched",
    "test_cublasZgerc_v2",
    "test_cublasZgeru_v2",
    "test_cublasZgetrfBatched",
    "test_cublasZgetriBatched",
    "test_cublasZgetrsBatched",
    "test_cublasZhbmv_v2",
    "test_cublasZhemm_v2",
    "test_cublasZhemv_v2",
    "test_cublasZher2k_v2",
    "test_cublasZher2_v2",
    "test_cublasZherk_v2",
    "test_cublasZherkx",
    "test_cublasZher_v2",
    "test_cublasZhpmv_v2",
    "test_cublasZhpr2_v2",
    "test_cublasZhpr_v2",
    "test_cublasZmatinvBatched",
    "test_cublasZrotg_v2",
    "test_cublasZrot_v2",
    "test_cublasZscal_v2",
    "test_cublasZswap_v2",
    "test_cublasZsymm_v2",
    "test_cublasZsymv_v2",
    "test_cublasZsyr2k_v2",
    "test_cublasZsyr2_v2",
    "test_cublasZsyrk_v2",
    "test_cublasZsyrkx",
    "test_cublasZsyr_v2",
    "test_cublasZtbmv_v2",
    "test_cublasZtbsv_v2",
    "test_cublasZtpmv_v2",
    "test_cublasZtpsv_v2",
    "test_cublasZtpttr",
    "test_cublasZtrmm_v2",
    "test_cublasZtrmv_v2",
    "test_cublasZtrsmBatched",
    "test_cublasZtrsm_v2",
    "test_cublasZtrsv_v2",
    "test_cublasZtrttp",
]

# ===================== CUFFT 全部用例 =====================
CUFFT_TESTS = [
    "test_cufftCreate",
    "test_cufftDestroy",
    "test_cufftEstimate1d",
    "test_cufftEstimate2d",
    "test_cufftEstimate3d",
    "test_cufftEstimateMany",
    "test_cufftExecC2C",
    "test_cufftExecC2R",
    "test_cufftExecD2Z",
    "test_cufftExecR2C",
    "test_cufftExecZ2D",
    "test_cufftExecZ2Z",
    "test_cufftGetProperty",
    "test_cufftGetSize",
    "test_cufftGetSize1d",
    "test_cufftGetSize2d",
    "test_cufftGetSize3d",
    "test_cufftGetSizeMany",
    "test_cufftGetSizeMany64",
    "test_cufftGetVersion",
    "test_cufftMakePlan1d",
    "test_cufftMakePlan2d",
    "test_cufftMakePlan3d",
    "test_cufftMakePlanMany",
    "test_cufftMakePlanMany64",
    "test_cufftPlan1d",
    "test_cufftPlan2d",
    "test_cufftPlan3d",
    "test_cufftPlanMany",
    "test_cufftSetAutoAllocation",
    "test_cufftSetStream",
    "test_cufftSetWorkArea",
    "test_cufftXtClearCallback",
    "test_cufftXtExec",
    "test_cufftXtExecDescriptor",
    "test_cufftXtExecDescriptorC2C",
    "test_cufftXtExecDescriptorC2R",
    "test_cufftXtExecDescriptorD2Z",
    "test_cufftXtExecDescriptorR2C",
    "test_cufftXtExecDescriptorZ2D",
    "test_cufftXtExecDescriptorZ2Z",
    "test_cufftXtFree",
    "test_cufftXtGetSizeMany",
    "test_cufftXtMakePlanMany",
    "test_cufftXtMalloc",
    "test_cufftXtMemcpy",
    "test_cufftXtQueryPlan",
    "test_cufftXtSetCallback",
    "test_cufftXtSetCallbackSharedSize",
    "test_cufftXtSetGPUs",
    "test_cufftXtSetWorkArea",
    "test_cufftXtSetWorkAreaPolicy",
]

# ===================== NCCL 全部用例 =====================
NCCL_TESTS = [
    "test_ncclAllGather",
    "test_ncclAllReduce",
    "test_ncclBcast",
    "test_ncclBroadcast",
    "test_ncclCommAbort",
    "test_ncclCommCount",
    "test_ncclCommCuDevice",
    "test_ncclCommDestroy",
    "test_ncclCommGetAsyncError",
    "test_ncclCommInitAll",
    "test_ncclCommInitRank",
    "test_ncclCommUserRank",
    "test_ncclGetErrorString",
    "test_ncclGetUniqueId",
    "test_ncclGetVersion",
    "test_ncclGroupEnd",
    "test_ncclGroupStart",
    "test_ncclReduce",
    "test_ncclReduceScatter",
]

# ===================== 测试执行函数 =====================
def run_test(bin_path):
    try:
        ret = subprocess.run([bin_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
        return ret.returncode == 0
    except:
        return False

def run_module(module_name, test_dir, test_list):
    print("=" * 70)
    print(f"               {module_name} 测试")
    print("=" * 70)

    total = len(test_list)
    passed = 0
    failed = []

    for test in test_list:
        path = os.path.join(test_dir, test)
        if not os.path.exists(path):
            print(f"❌ {test} -> 不存在")
            failed.append(test)
            continue

        print(f"\n▶ 运行: {test}")
        ok = run_test(path)
        if ok:
            print(f"✅ 通过")
            passed += 1
        else:
            print(f"❌ 失败")
            failed.append(test)

    print("\n" + "=" * 70)
    print(f"                     {module_name} 报告")
    print("=" * 70)
    print(f"📌 总用例：{total}")
    print(f"✅ 通过：{passed}")
    print(f"❌ 失败：{len(failed)}")
    print(f"📊 通过率：{passed/total*100:.2f}%" if total else "📊 通过率：0%")
    if mode == "runtime":
        print(f"📈 覆盖率(based on 365):{passed/365*100:.2f}%")
    elif mode == "cublas":
        print(f"📈 覆盖率(based on 343):{passed/343*100:.2f}%")
    elif mode == "cufft":
        print(f"📈 覆盖率(based on 53):{passed/53*100:.2f}%")
    elif mode == "nccl":
        print(f"📈 覆盖率(based on 19):{passed/TOTAL_API_NCCL*100:.2f}%")
    else:
        sys.exit(1)
    print("=" * 70)

    if failed:
        print("\n失败用例列表：")
        for f in failed:
            print(f"  ❌ {f}")

    return len(failed)

# ===================== 入口 =====================
if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("用法：")
        print("  python3 test.py runtime   # 只跑 Runtime")
        print("  python3 test.py cublas    # 只跑 CUBLAS")
        print("  python3 test.py cufft     # 只跑 cuFFT")
        print("  python3 test.py nccl      # 只跑 NCCL")
        sys.exit(1)

    mode = sys.argv[1]
    if mode == "runtime":
        fail_cnt = run_module("CUDA Runtime", RUNTIME_DIR, RUNTIME_TESTS)
    elif mode == "cublas":
        fail_cnt = run_module("CUBLAS", CUBLAS_DIR, CUBLAS_TESTS)
    elif mode == "cufft":
        fail_cnt = run_module("cuFFT", CUFFT_DIR, CUFFT_TESTS)
    elif mode == "nccl":
        fail_cnt = run_module("NCCL", NCCL_DIR, NCCL_TESTS)
    else:
        print("不支持的模块！可选：runtime / cublas / cufft / nccl")
        sys.exit(1)

    sys.exit(fail_cnt)
