#pragma once
/* Auto-generated from src/driver/driver_fun_convert.cpp - run generate_driver_tests.ps1 */
#include <cuda.h>
#include "driver_smoke_types.h"
#include <UPTK.h>

#ifdef __cplusplus
extern "C" {
#endif

UPTKError UPArray3DCreate(UPTKarray * pHandle,const UPTK_ARRAY3D_DESCRIPTOR * pAllocateArray);
UPTKError UPArray3DGetDescriptor(UPTK_ARRAY3D_DESCRIPTOR * pArrayDescriptor, UPTKarray hArray);
UPTKError UPArrayCreate(UPTKarray * pHandle,const UPTK_ARRAY_DESCRIPTOR * pAllocateArray);
UPTKError UPArrayDestroy(UPTKarray hArray);
UPTKError UPArrayGetDescriptor(UPTK_ARRAY_DESCRIPTOR * pArrayDescriptor,UPTKarray hArray);
UPTKError UPCtxAttach(UPTKcontext * pctx,unsigned int flags);
UPTKError UPCtxCreate(UPTKcontext * pctx,unsigned int flags,UPTKdevice dev);
UPTKError UPCtxDestroy(UPTKcontext ctx);
UPTKError UPCtxDetach(UPTKcontext ctx);
UPTKError UPCtxDisablePeerAccess(UPTKcontext peerContext);
UPTKError UPCtxEnablePeerAccess(UPTKcontext peerContext,unsigned int Flags);
UPTKError UPCtxGetApiVersion(UPTKcontext ctx,unsigned int * version);
UPTKError UPCtxGetCacheConfig(UPTKfunc_cache * pconfig);
UPTKError UPCtxGetCurrent(UPTKcontext * pctx);
UPTKError UPCtxGetDevice(UPTKdevice * device);
UPTKError UPCtxGetFlags(unsigned int * flags);
UPTKError UPCtxGetLimit(size_t * pvalue,UPTKlimit limit);
UPTKError UPCtxGetSharedMemConfig(UPTKsharedconfig * pConfig);
UPTKError UPCtxGetStreamPriorityRange(int * leastPriority,int * greatestPriority);
UPTKError UPCtxPopCurrent(UPTKcontext * pctx);
UPTKError UPCtxPushCurrent(UPTKcontext ctx);
UPTKError UPCtxSetCacheConfig(UPTKfunc_cache config);
UPTKError UPCtxSetCurrent(UPTKcontext ctx);
UPTKError UPCtxSetLimit(UPTKlimit limit,size_t value);
UPTKError UPCtxSetSharedMemConfig(UPTKsharedconfig config);
UPTKError UPCtxSynchronize(void);
UPTKError UPDestroyExternalMemory(UPTKExternalMemory_t extMem);
UPTKError UPDestroyExternalSemaphore(UPTKExternalSemaphore_t extSem);
UPTKError UPDeviceCanAccessPeer(int * canAccessPeer,UPTKdevice dev,UPTKdevice peerDev);
UPTKError UPDeviceComputeCapability(int * major,int * minor,UPTKdevice dev);
UPTKError UPDeviceGet(UPTKdevice * device,int ordinal);
UPTKError UPDeviceGetAttribute(int * pi,UPTKDeviceAttr attrib,UPTKdevice dev);
UPTKError UPDeviceGetByPCIBusId(UPTKdevice * dev,const char * pciBusId);
UPTKError UPDeviceGetCount(int * count);
UPTKError UPDeviceGetLuid(char * luid,unsigned int * deviceNodeMask,UPTKdevice dev);
UPTKError UPDeviceGetName(char * name,int len,UPTKdevice dev);
UPTKError UPDeviceGetNvSciSyncAttributes(void * nvSciSyncAttrList,UPTKdevice dev,int flags);
UPTKError UPDeviceGetP2PAttribute(int * value,UPTKdevice_P2PAttribute attrib,UPTKdevice srcDevice,UPTKdevice dstDevice);
UPTKError UPDeviceGetPCIBusId(char * pciBusId,int len,UPTKdevice dev);
UPTKError UPDeviceGetProperties(UPTKdevprop * prop,UPTKdevice dev);
UPTKError UPDeviceGetUuid(UPTKuuid * uuid,UPTKdevice dev);
UPTKError UPDevicePrimaryCtxGetState(UPTKdevice dev,unsigned int * flags,int * active);
UPTKError UPDevicePrimaryCtxRelease(UPTKdevice dev);
UPTKError UPDevicePrimaryCtxReset(UPTKdevice dev);
UPTKError UPDevicePrimaryCtxRetain(UPTKcontext * pctx,UPTKdevice dev);
UPTKError UPDevicePrimaryCtxSetFlags(UPTKdevice dev,unsigned int flags);
UPTKError UPDeviceTotalMem_v2(size_t * bytes,UPTKdevice dev);
UPTKError UPDriverGetVersion(int * driverVersion);
UPTKError UPEventCreate(UPTKEvent_t * phEvent,unsigned int Flags);
UPTKError UPEventDestroy(UPTKEvent_t hEvent);
UPTKError UPEventElapsedTime(float * pMilliseconds,UPTKEvent_t hStart,UPTKEvent_t hEnd);
UPTKError UPEventQuery(UPTKEvent_t hEvent);
UPTKError UPEventRecord(UPTKEvent_t hEvent,UPTKStream_t hStream);
UPTKError UPEventSynchronize(UPTKEvent_t hEvent);
UPTKError UPExternalMemoryGetMappedBuffer(UPTKdeviceptr * devPtr,UPTKExternalMemory_t extMem,const UPTK_EXTERNAL_MEMORY_BUFFER_DESC * bufferDesc);
UPTKError UPExternalMemoryGetMappedMipmappedArray(UPTKMipmappedArray_t * mipmap,UPTKExternalMemory_t extMem,const UPTK_EXTERNAL_MEMORY_MIPMAPPED_ARRAY_DESC * mipmapDesc);
UPTKError UPFuncGetAttribute(int * pi,UPTKfunction_attribute attrib,UPTKfunction hfunc);
UPTKError UPFuncSetAttribute(UPTKfunction hfunc,UPTKfunction_attribute attrib,int value);
UPTKError UPFuncSetBlockShape(UPTKfunction hfunc,int x,int y,int z);
UPTKError UPFuncSetCacheConfig(UPTKfunction hfunc,UPTKfunc_cache config);
UPTKError UPFuncSetSharedMemConfig(UPTKfunction hfunc,UPTKsharedconfig config);
UPTKError UPFuncSetSharedSize(UPTKfunction hfunc,unsigned int bytes);
UPTKError UPGLGetDevices(unsigned int * pCudaDeviceCount,UPTKdevice * pCudaDevices,unsigned int cudaDeviceCount,UPTKGLDeviceList deviceList);
UPTKError UPGetErrorName(UPTKError error,const char ** pStr);
UPTKError UPGetErrorString(UPTKError error, const char ** pStr);
UPTKError UPGetExportTable(const void ** ppExportTable,const UPTKuuid * pExportTableId);
UPTKError UPGraphAddChildGraphNode(UPTKGraphNode_t * phGraphNode,UPTKGraph_t hGraph,const UPTKGraphNode_t * dependencies,size_t numDependencies,UPTKGraph_t childGraph);
UPTKError UPGraphAddDependencies(UPTKGraph_t hGraph,const UPTKGraphNode_t * from,const UPTKGraphNode_t * to,size_t numDependencies);
UPTKError UPGraphAddEmptyNode(UPTKGraphNode_t * phGraphNode,UPTKGraph_t hGraph,const UPTKGraphNode_t * dependencies,size_t numDependencies);
UPTKError UPGraphAddHostNode(UPTKGraphNode_t * phGraphNode,UPTKGraph_t hGraph,const UPTKGraphNode_t * dependencies,size_t numDependencies,const UPTK_HOST_NODE_PARAMS * nodeParams);
UPTKError UPGraphAddMemcpyNode(UPTKGraphNode_t * phGraphNode,UPTKGraph_t hGraph,const UPTKGraphNode_t * dependencies,size_t numDependencies,const UPTK_MEMCPY3D * copyParams,UPTKcontext ctx);
UPTKError UPGraphAddMemsetNode(UPTKGraphNode_t * phGraphNode,UPTKGraph_t hGraph,const UPTKGraphNode_t * dependencies,size_t numDependencies,const UPTK_MEMSET_NODE_PARAMS * memsetParams,UPTKcontext ctx);
UPTKError UPGraphChildGraphNodeGetGraph(UPTKGraphNode_t hNode,UPTKGraph_t * phGraph);
UPTKError UPGraphClone(UPTKGraph_t * phGraphClone,UPTKGraph_t originalGraph);
UPTKError UPGraphCreate(UPTKGraph_t * phGraph,unsigned int flags);
UPTKError UPGraphDestroy(UPTKGraph_t hGraph);
UPTKError UPGraphDestroyNode(UPTKGraphNode_t hNode);
UPTKError UPGraphExecDestroy(UPTKGraphExec_t hGraphExec);
UPTKError UPGraphExecHostNodeSetParams(UPTKGraphExec_t hGraphExec,UPTKGraphNode_t hNode,const UPTK_HOST_NODE_PARAMS * nodeParams);
UPTKError UPGraphExecMemcpyNodeSetParams(UPTKGraphExec_t hGraphExec,UPTKGraphNode_t hNode,const UPTK_MEMCPY3D * copyParams,UPTKcontext ctx);
UPTKError UPGraphExecMemsetNodeSetParams(UPTKGraphExec_t hGraphExec,UPTKGraphNode_t hNode,const UPTK_MEMSET_NODE_PARAMS * memsetParams,UPTKcontext ctx);
UPTKError UPGraphGetEdges(UPTKGraph_t hGraph,UPTKGraphNode_t * from,UPTKGraphNode_t * to,size_t * numEdges);
UPTKError UPGraphGetNodes(UPTKGraph_t hGraph,UPTKGraphNode_t * nodes,size_t * numNodes);
UPTKError UPGraphGetRootNodes(UPTKGraph_t hGraph,UPTKGraphNode_t * rootNodes,size_t * numRootNodes);
UPTKError UPGraphHostNodeGetParams(UPTKGraphNode_t hNode,UPTK_HOST_NODE_PARAMS * nodeParams);
UPTKError UPGraphHostNodeSetParams(UPTKGraphNode_t hNode,const UPTK_HOST_NODE_PARAMS * nodeParams);
UPTKError UPGraphLaunch(UPTKGraphExec_t hGraphExec,UPTKStream_t hStream);
UPTKError UPGraphMemsetNodeGetParams(UPTKGraphNode_t hNode,UPTK_MEMSET_NODE_PARAMS * nodeParams);
UPTKError UPGraphMemsetNodeSetParams(UPTKGraphNode_t hNode,const UPTK_MEMSET_NODE_PARAMS * nodeParams);
UPTKError UPGraphNodeFindInClone(UPTKGraphNode_t * phNode,UPTKGraphNode_t hOriginalNode,UPTKGraph_t hClonedGraph);
UPTKError UPGraphNodeGetDependencies(UPTKGraphNode_t hNode,UPTKGraphNode_t * dependencies,size_t * numDependencies);
UPTKError UPGraphNodeGetDependentNodes(UPTKGraphNode_t hNode,UPTKGraphNode_t * dependentNodes,size_t * numDependentNodes);
UPTKError UPGraphNodeGetType(UPTKGraphNode_t hNode,UPTKGraphNodeType * type);
UPTKError UPGraphRemoveDependencies(UPTKGraph_t hGraph,const UPTKGraphNode_t * from,const UPTKGraphNode_t * to,size_t numDependencies);
UPTKError UPGraphicsGLRegisterBuffer(UPTKGraphicsResource_t * pCudaResource,GLuint buffer,unsigned int Flags);
UPTKError UPGraphicsGLRegisterImage(UPTKGraphicsResource_t * pCudaResource,GLuint image,GLenum target,unsigned int Flags);
UPTKError UPGraphicsMapResources(unsigned int count,UPTKGraphicsResource_t * resources,UPTKStream_t hStream);
UPTKError UPGraphicsResourceGetMappedPointer_v2(UPTKdeviceptr * pDevPtr,size_t * pSize,UPTKGraphicsResource_t resource);
UPTKError UPGraphicsSubResourceGetMappedArray(UPTKarray * pArray,UPTKGraphicsResource_t resource,unsigned int arrayIndex,unsigned int mipLevel);
UPTKError UPGraphicsUnregisterResource(UPTKGraphicsResource_t resource);
UPTKError UPGraphicsUnmapResources(unsigned int count,UPTKGraphicsResource_t * resources,UPTKStream_t hStream);
UPTKError UPGraphicsResourceGetMappedMipmappedArray(UPTKMipmappedArray_t * pMipmappedArray,UPTKGraphicsResource_t resource);
UPTKError UPGraphicsResourceSetMapFlags(UPTKGraphicsResource_t resource,unsigned int flags);
UPTKError UPImportExternalMemory(UPTKExternalMemory_t * extMem_out,const UPTK_EXTERNAL_MEMORY_HANDLE_DESC * memHandleDesc);
UPTKError UPImportExternalSemaphore(UPTKExternalSemaphore_t * extSem_out,const UPTK_EXTERNAL_SEMAPHORE_HANDLE_DESC * semHandleDesc);
UPTKError UPInit(unsigned int Flags);
UPTKError UPIpcCloseMemHandle(UPTKdeviceptr dptr);
UPTKError UPIpcGetEventHandle(UPTKIpcEventHandle_t * pHandle,UPTKEvent_t event);
UPTKError UPIpcGetMemHandle(UPTKIpcMemHandle_t * pHandle,UPTKdeviceptr dptr);
UPTKError UPIpcOpenEventHandle(UPTKEvent_t * phEvent,UPTKIpcEventHandle_t handle);
UPTKError UPIpcOpenMemHandle(UPTKdeviceptr * pdptr,UPTKIpcMemHandle_t handle,unsigned int Flags);
UPTKError UPLaunch(UPTKfunction f);
UPTKError UPLaunchCooperativeKernel(UPTKfunction f,unsigned int gridDimX,unsigned int gridDimY,unsigned int gridDimZ,unsigned int blockDimX,unsigned int blockDimY,unsigned int blockDimZ,unsigned int sharedMemBytes,UPTKStream_t hStream,void ** kernelParams);
UPTKError UPLaunchCooperativeKernelMultiDevice(UPTK_LAUNCH_PARAMS * launchParamsList,unsigned int numDevices,unsigned int flags);
UPTKError UPLaunchGrid(UPTKfunction f,int grid_width,int grid_height);
UPTKError UPLaunchGridAsync(UPTKfunction f,int grid_width,int grid_height,UPTKStream_t hStream);
UPTKError UPLaunchHostFunc(UPTKStream_t hStream,UPTKhostFn fn,void * userData);
UPTKError UPLaunchKernel(UPTKfunction f,unsigned int gridDimX,unsigned int gridDimY,unsigned int gridDimZ,unsigned int blockDimX,unsigned int blockDimY,unsigned int blockDimZ,unsigned int sharedMemBytes,UPTKStream_t hStream,void ** kernelParams,void ** extra);
UPTKError UPLinkAddData(UPTKlinkState state,UPTKjitInputType type,void * data,size_t size,const char * name,unsigned int numOptions,UPTKjit_option * options,void ** optionValues);
UPTKError UPLinkAddFile(UPTKlinkState state,UPTKjitInputType type,const char * path,unsigned int numOptions,UPTKjit_option * options,void ** optionValues);
UPTKError UPLinkComplete(UPTKlinkState state,void ** cubinOut,size_t * sizeOut);
UPTKError UPLinkCreate(unsigned int numOptions,UPTKjit_option * options,void ** optionValues,UPTKlinkState * stateOut);
UPTKError UPLinkDestroy(UPTKlinkState state);
UPTKError UPMemAddressFree(UPTKdeviceptr ptr,size_t size);
UPTKError UPMemAddressReserve(UPTKdeviceptr * ptr,size_t size,size_t alignment,UPTKdeviceptr addr,unsigned long long flags);
UPTKError UPMemAdvise(UPTKdeviceptr devPtr,size_t count,UPTKmem_advise advice,UPTKdevice device);
UPTKError UPMemAlloc_v2(UPTKdeviceptr * dptr,size_t bytesize);
UPTKError UPMemAllocHost(void ** pp, size_t bytesize);
UPTKError UPMemAllocManaged(UPTKdeviceptr * dptr,size_t bytesize,unsigned int flags);
UPTKError UPMemAllocPitch_v2(UPTKdeviceptr * dptr,size_t * pPitch, size_t WidthInBytes, size_t Height,unsigned int ElementSizeBytes);
UPTKError UPMemCreate(UPTKmemGenericAllocationHandle * handle,size_t size,const UPTKmemAllocationProp * prop,unsigned long long flags);
UPTKError UPMemExportToShareableHandle(void * shareableHandle,UPTKmemGenericAllocationHandle handle,UPTKMemAllocationHandleType handleType,unsigned long long flags);
UPTKError UPMemFree(UPTKdeviceptr dptr);
UPTKError UPMemFreeHost(void * p);
UPTKError UPMemGetAccess(unsigned long long * flags,const UPTKMemLocation * location,UPTKdeviceptr ptr);
UPTKError UPMemGetAddressRange_v2(UPTKdeviceptr * pbase,size_t * psize,UPTKdeviceptr dptr);
UPTKError UPMemGetAllocationGranularity(size_t * granularity,const UPTKmemAllocationProp * prop,UPTKmemAllocationGranularity_flags option);
UPTKError UPMemGetAllocationPropertiesFromHandle(UPTKmemAllocationProp * prop,UPTKmemGenericAllocationHandle handle);
UPTKError UPMemGetInfo_v2(size_t * free, size_t * total);
UPTKError UPMemHostAlloc(void ** pp, size_t bytesize, unsigned int Flags);
UPTKError UPMemHostGetDevicePointer(UPTKdeviceptr * pdptr,void * p,unsigned int Flags);
UPTKError UPMemHostGetFlags(unsigned int * pFlags,void * p);
UPTKError UPMemHostRegister(void * p,size_t bytesize,unsigned int Flags);
UPTKError UPMemHostUnregister(void * p);
UPTKError UPMemImportFromShareableHandle(UPTKmemGenericAllocationHandle * handle,void * osHandle,UPTKMemAllocationHandleType shHandleType);
UPTKError UPMemMap(UPTKdeviceptr ptr,size_t size,size_t offset,UPTKmemGenericAllocationHandle handle,unsigned long long flags);
UPTKError UPMemPrefetchAsync(UPTKdeviceptr devPtr,size_t count,UPTKdevice dstDevice,UPTKStream_t hStream);
UPTKError UPMemRangeGetAttribute(void * data,size_t dataSize,UPTKmem_range_attribute attribute,UPTKdeviceptr devPtr,size_t count);
UPTKError UPMemRangeGetAttributes(void ** data,size_t * dataSizes,UPTKmem_range_attribute * attributes,size_t numAttributes,UPTKdeviceptr devPtr,size_t count);
UPTKError UPMemRelease(UPTKmemGenericAllocationHandle handle);
UPTKError UPMemSetAccess(UPTKdeviceptr ptr,size_t size,const UPTKMemAccessDesc * desc,size_t count);
UPTKError UPMemUnmap(UPTKdeviceptr ptr,size_t size);
UPTKError UPMemcpy(UPTKdeviceptr dst,UPTKdeviceptr src,size_t ByteCount);
UPTKError UPMemcpy2DAsync_v2(const UPTK_MEMCPY2D * pCopy,UPTKStream_t hStream);
UPTKError UPMemcpy2DUnaligned_v2(const UPTK_MEMCPY2D * pCopy);
UPTKError UPMemcpy2D_v2(const UPTK_MEMCPY2D * pCopy);
UPTKError UPMemcpy3DAsync_v2(const UPTK_MEMCPY3D * pCopy,UPTKStream_t hStream);
UPTKError UPMemcpy3DPeer(const UPTK_MEMCPY3D_PEER * pCopy);
UPTKError UPMemcpy3DPeerAsync(const UPTK_MEMCPY3D_PEER * pCopy,UPTKStream_t hStream);
UPTKError UPMemcpy3D_v2(const UPTK_MEMCPY3D * pCopy);
UPTKError UPMemcpyAsync(UPTKdeviceptr dst,UPTKdeviceptr src,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyAtoA_v2(UPTKarray dstArray,size_t dstOffset,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyAtoD_v2(UPTKdeviceptr dstDevice,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyAtoHAsync_v2(void * dstHost,UPTKarray srcArray,size_t srcOffset,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyAtoH_v2(void * dstHost,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyDtoA_v2(UPTKarray dstArray,size_t dstOffset,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyDtoDAsync_v2(UPTKdeviceptr dstDevice,UPTKdeviceptr srcDevice,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyDtoD_v2(UPTKdeviceptr dstDevice,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyDtoHAsync_v2(void * dstHost,UPTKdeviceptr srcDevice,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyDtoH_v2(void * dstHost,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyHtoAAsync_v2(UPTKarray dstArray,size_t dstOffset,const void * srcHost,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyHtoA_v2(UPTKarray dstArray,size_t dstOffset,const void * srcHost,size_t ByteCount);
UPTKError UPMemcpyHtoDAsync_v2(UPTKdeviceptr dstDevice,const void * srcHost,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyHtoD_v2(UPTKdeviceptr dstDevice,const void * srcHost,size_t ByteCount);
UPTKError UPMemcpyPeer(UPTKdeviceptr dstDevice,UPTKcontext dstContext,UPTKdeviceptr srcDevice,UPTKcontext srcContext,size_t ByteCount);
UPTKError UPMemcpyPeerAsync(UPTKdeviceptr dstDevice,UPTKcontext dstContext,UPTKdeviceptr srcDevice,UPTKcontext srcContext,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemsetD16Async(UPTKdeviceptr dstDevice,unsigned short us,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD16_v2(UPTKdeviceptr dstDevice,unsigned short us,size_t N);
UPTKError UPMemsetD2D16Async(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned short us,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPMemsetD2D16_v2(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned short us,size_t Width,size_t Height);
UPTKError UPMemsetD2D32Async(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned int ui,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPMemsetD2D32_v2(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned int ui,size_t Width,size_t Height);
UPTKError UPMemsetD2D8Async(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned char uc,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPMemsetD2D8_v2(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned char uc,size_t Width,size_t Height);
UPTKError UPMemsetD32Async(UPTKdeviceptr dstDevice,unsigned int ui,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD32_v2(UPTKdeviceptr dstDevice,unsigned int ui,size_t N);
UPTKError UPMemsetD8Async(UPTKdeviceptr dstDevice,unsigned char uc,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD8_v2(UPTKdeviceptr dstDevice,unsigned char uc,size_t N);
UPTKError UPMipmappedArrayCreate(UPTKMipmappedArray_t * pHandle,const UPTK_ARRAY3D_DESCRIPTOR * pMipmappedArrayDesc,unsigned int numMipmapLevels);
UPTKError UPMipmappedArrayDestroy(UPTKMipmappedArray_t hMipmappedArray);
UPTKError UPMipmappedArrayGetLevel(UPTKarray * pLevelArray,UPTKMipmappedArray_t hMipmappedArray,unsigned int level);
UPTKError UPModuleGetFunction(UPTKfunction * hfunc,UPTKmodule hmod,const char * name);
UPTKError UPModuleGetGlobal_v2(UPTKdeviceptr * dptr, size_t * bytes,UPTKmodule hmod,const char * name);
UPTKError UPModuleGetSurfRef(UPTKsurfref * pSurfRef,UPTKmodule hmod,const char * name);
UPTKError UPModuleGetTexRef(UPTKtexref * pTexRef,UPTKmodule hmod,const char * name);
UPTKError UPModuleLoad(UPTKmodule * module,const char * fname);
UPTKError UPModuleLoadData(UPTKmodule * module,const void * image);
UPTKError UPModuleLoadDataEx(UPTKmodule * module,const void * image,unsigned int numOptions,UPTKjit_option * options,void ** optionValues);
UPTKError UPModuleLoadFatBinary(UPTKmodule * module,const void * fatCubin);
UPTKError UPModuleUnload(UPTKmodule hmod);
UPTKError UPOccupancyMaxActiveBlocksPerMultiprocessor(int * numBlocks,UPTKfunction func,int blockSize,size_t dynamicSMemSize);
UPTKError UPOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(int * numBlocks,UPTKfunction func,int blockSize,size_t dynamicSMemSize,unsigned int flags);
UPTKError UPOccupancyMaxPotentialBlockSize(int * minGridSize,int * blockSize,UPTKfunction func,UPTKoccupancyB2DSize blockSizeToDynamicSMemSize,size_t dynamicSMemSize,int blockSizeLimit);
UPTKError UPOccupancyMaxPotentialBlockSizeWithFlags(int * minGridSize,int * blockSize,UPTKfunction func,UPTKoccupancyB2DSize blockSizeToDynamicSMemSize,size_t dynamicSMemSize,int blockSizeLimit,unsigned int flags);
UPTKError UPParamSetSize(UPTKfunction hfunc,unsigned int numbytes);
UPTKError UPParamSetTexRef(UPTKfunction hfunc,int texunit,UPTKtexref hTexRef);
UPTKError UPParamSetf(UPTKfunction hfunc,int offset,float value);
UPTKError UPParamSeti(UPTKfunction hfunc,int offset,unsigned int value);
UPTKError UPParamSetv(UPTKfunction hfunc,int offset,void * ptr,unsigned int numbytes);
UPTKError UPPointerGetAttribute(void * data,UPTKpointer_attribute attribute,UPTKdeviceptr ptr);
UPTKError UPPointerGetAttributes(unsigned int numAttributes,UPTKpointer_attribute * attributes,void ** data,UPTKdeviceptr ptr);
UPTKError UPPointerSetAttribute(const void * value,UPTKpointer_attribute attribute,UPTKdeviceptr ptr);
UPTKError UPProfilerInitialize(const char * configFile,const char * outputFile,UPTKoutput_mode outputMode);
UPTKError UPProfilerStart(void);
UPTKError UPProfilerStop(void);
UPTKError UPSignalExternalSemaphoresAsync(const UPTKExternalSemaphore_t * extSemArray,const UPTK_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS * paramsArray,unsigned int numExtSems,UPTKStream_t stream);
UPTKError UPStreamAddCallback(UPTKStream_t hStream,UPTKstreamCallback callback,void * userData,unsigned int flags);
UPTKError UPStreamAttachMemAsync(UPTKStream_t hStream,UPTKdeviceptr dptr,size_t length,unsigned int flags);
UPTKError UPStreamBatchMemOp(UPTKStream_t stream,unsigned int count,UPTKstreamBatchMemOpParams * paramArray,unsigned int flags);
UPTKError UPStreamBeginCapture_v2(UPTKStream_t hStream,UPTKStreamCaptureMode mode);
UPTKError UPStreamCreate(UPTKStream_t * phStream,unsigned int Flags);
UPTKError UPStreamCreateWithPriority(UPTKStream_t * phStream,unsigned int flags,int priority);
UPTKError UPStreamDestroy(UPTKStream_t hStream);
UPTKError UPStreamEndCapture(UPTKStream_t hStream,UPTKGraph_t * phGraph);
UPTKError UPStreamGetCtx(UPTKStream_t hStream,UPTKcontext * pctx);
UPTKError UPStreamGetFlags(UPTKStream_t hStream,unsigned int * flags);
UPTKError UPStreamGetPriority(UPTKStream_t hStream,int * priority);
UPTKError UPStreamIsCapturing(UPTKStream_t hStream,UPTKStreamCaptureStatus * captureStatus);
UPTKError UPStreamQuery(UPTKStream_t hStream);
UPTKError UPStreamSynchronize(UPTKStream_t hStream);
UPTKError UPStreamWaitEvent(UPTKStream_t hStream,UPTKEvent_t hEvent,unsigned int Flags);
UPTKError UPStreamWriteValue32(UPTKStream_t stream,UPTKdeviceptr addr,cuuint32_t value,unsigned int flags);
UPTKError UPStreamWriteValue64(UPTKStream_t stream,UPTKdeviceptr addr,cuuint64_t value,unsigned int flags);
UPTKError UPSurfObjectCreate(UPTKSurfaceObject_t * pSurfObject,const UPTK_RESOURCE_DESC * pResDesc);
UPTKError UPSurfObjectDestroy(UPTKSurfaceObject_t surfObject);
UPTKError UPSurfObjectGetResourceDesc(UPTK_RESOURCE_DESC * pResDesc,UPTKSurfaceObject_t surfObject);
UPTKError UPSurfRefGetArray(UPTKarray * phArray,UPTKsurfref hSurfRef);
UPTKError UPSurfRefSetArray(UPTKsurfref hSurfRef,UPTKarray hArray,unsigned int Flags);
UPTKError UPTexObjectCreate(UPTKTextureObject_t * pTexObject,const UPTK_RESOURCE_DESC * pResDesc,const UPTK_TEXTURE_DESC * pTexDesc,const UPTK_RESOURCE_VIEW_DESC * pResViewDesc);
UPTKError UPTexObjectDestroy(UPTKTextureObject_t texObject);
UPTKError UPTexObjectGetResourceDesc(UPTK_RESOURCE_DESC * pResDesc,UPTKTextureObject_t texObject);
UPTKError UPTexObjectGetResourceViewDesc(UPTK_RESOURCE_VIEW_DESC * pResViewDesc,UPTKTextureObject_t texObject);
UPTKError UPTexObjectGetTextureDesc(UPTK_TEXTURE_DESC * pTexDesc,UPTKTextureObject_t texObject);
UPTKError UPTexRefCreate(UPTKtexref * pTexRef);
UPTKError UPTexRefDestroy(UPTKtexref hTexRef);
UPTKError UPTexRefGetAddress(UPTKdeviceptr * pdptr,UPTKtexref hTexRef);
UPTKError UPTexRefGetAddressMode(UPTKaddress_mode * pam,UPTKtexref hTexRef,int dim);
UPTKError UPTexRefGetArray(UPTKarray * phArray, UPTKtexref hTexRef);
UPTKError UPTexRefGetBorderColor(float * pBorderColor,UPTKtexref hTexRef);
UPTKError UPTexRefGetFilterMode(UPTKfilter_mode * pfm,UPTKtexref hTexRef);
UPTKError UPTexRefGetFlags(unsigned int * pFlags,UPTKtexref hTexRef);
UPTKError UPTexRefGetFormat(UPTKarray_format * pFormat,int * pNumChannels,UPTKtexref hTexRef);
UPTKError UPTexRefGetMaxAnisotropy(int * pmaxAniso,UPTKtexref hTexRef);
UPTKError UPTexRefGetMipmapFilterMode(UPTKfilter_mode * pfm,UPTKtexref hTexRef);
UPTKError UPTexRefGetMipmapLevelBias(float * pbias,UPTKtexref hTexRef);
UPTKError UPTexRefGetMipmapLevelClamp(float * pminMipmapLevelClamp,float * pmaxMipmapLevelClamp,UPTKtexref hTexRef);
UPTKError UPTexRefGetMipmappedArray(UPTKMipmappedArray_t * phMipmappedArray,UPTKtexref hTexRef);
UPTKError UPTexRefSetAddress_v2(size_t * ByteOffset,UPTKtexref hTexRef,UPTKdeviceptr dptr,size_t bytes);
UPTKError UPTexRefSetAddress2D_v3(UPTKtexref hTexRef,const UPTK_ARRAY_DESCRIPTOR * desc,UPTKdeviceptr dptr,size_t Pitch);
UPTKError UPTexRefSetAddressMode(UPTKtexref hTexRef,int dim,UPTKaddress_mode am);
UPTKError UPTexRefSetArray(UPTKtexref hTexRef,UPTKarray hArray,unsigned int Flags);
UPTKError UPTexRefSetBorderColor(UPTKtexref hTexRef,float * pBorderColor);
UPTKError UPTexRefSetFilterMode(UPTKtexref hTexRef,UPTKfilter_mode fm);
UPTKError UPTexRefSetFlags(UPTKtexref hTexRef,unsigned int Flags);
UPTKError UPTexRefSetFormat(UPTKtexref hTexRef,UPTKarray_format fmt,int NumPackedComponents);
UPTKError UPTexRefSetMaxAnisotropy(UPTKtexref hTexRef,unsigned int maxAniso);
UPTKError UPTexRefSetMipmapFilterMode(UPTKtexref hTexRef,UPTKfilter_mode fm);
UPTKError UPTexRefSetMipmapLevelBias(UPTKtexref hTexRef,float bias);
UPTKError UPTexRefSetMipmapLevelClamp(UPTKtexref hTexRef,float minMipmapLevelClamp,float maxMipmapLevelClamp);
UPTKError UPTexRefSetMipmappedArray(UPTKtexref hTexRef,UPTKMipmappedArray_t hMipmappedArray,unsigned int Flags);
UPTKError UPThreadExchangeStreamCaptureMode(UPTKStreamCaptureMode * mode);
UPTKError UPWaitExternalSemaphoresAsync(const UPTKExternalSemaphore_t * extSemArray,const UPTK_EXTERNAL_SEMAPHORE_WAIT_PARAMS * paramsArray,unsigned int numExtSems,UPTKStream_t stream);
UPTKError UPDeviceGetTexture1DLinearMaxWidth(size_t * maxWidthInElements, UPTKarray_format format, unsigned numChannels, UPTKdevice dev);
UPTKError UPDeviceSetMemPool(UPTKdevice dev, UPTKMemPool_t pool);
UPTKError UPDeviceGetMemPool(UPTKMemPool_t * pool, UPTKdevice dev);
UPTKError UPDeviceGetDefaultMemPool(UPTKMemPool_t * pool_out, UPTKdevice dev);
UPTKError UPFlushGPUDirectRDMAWrites(UPTKFlushGPUDirectRDMAWritesTarget target, UPTKFlushGPUDirectRDMAWritesScope scope);
UPTKError UPDeviceGetExecAffinitySupport(int * pi, UPTKexecAffinityType type, UPTKdevice dev);
UPTKError UPCtxCreate_v3(UPTKcontext * pctx, UPTKexecAffinityParam * paramsArray, int numParams, unsigned int flags, UPTKdevice dev);
UPTKError UPCtxResetPersistingL2Cache(void);
UPTKError UPCtxGetExecAffinity(UPTKexecAffinityParam * pExecAffinity, UPTKexecAffinityType type);
UPTKError UPModuleGetLoadingMode(UPTKmoduleLoadingMode * mode);
UPTKError UPArrayGetSparseProperties(UPTK_ARRAY_SPARSE_PROPERTIES * sparseProperties, UPTKarray array);
UPTKError UPMipmappedArrayGetSparseProperties(UPTK_ARRAY_SPARSE_PROPERTIES * sparseProperties, UPTKMipmappedArray_t mipmap);
UPTKError UPArrayGetMemoryRequirements(UPTK_ARRAY_MEMORY_REQUIREMENTS * memoryRequirements, UPTKarray array, UPTKdevice device);
UPTKError UPMipmappedArrayGetMemoryRequirements(UPTK_ARRAY_MEMORY_REQUIREMENTS * memoryRequirements, UPTKMipmappedArray_t mipmap, UPTKdevice device);
UPTKError UPArrayGetPlane(UPTKarray * pPlaneArray, UPTKarray hArray, unsigned int planeIdx);
UPTKError UPMemGetHandleForAddressRange(void * handle, UPTKdeviceptr dptr, size_t size, UPTKmemRangeHandleType handleType, unsigned long long flags);
UPTKError UPMemMapArrayAsync(UPTKarrayMapInfo * mapInfoList, unsigned int count, UPTKStream_t hStream);
UPTKError UPMemRetainAllocationHandle(UPTKmemGenericAllocationHandle * handle, void * addr);
UPTKError UPMemFreeAsync(UPTKdeviceptr dptr, UPTKStream_t hStream);
UPTKError UPMemAllocAsync(UPTKdeviceptr * dptr, size_t bytesize, UPTKStream_t hStream);
UPTKError UPMemPoolTrimTo(UPTKMemPool_t pool, size_t minBytesToKeep);
UPTKError UPMemPoolSetAttribute(UPTKMemPool_t pool, UPTKmemPool_attribute attr, void * value);
UPTKError UPMemPoolGetAttribute(UPTKMemPool_t pool, UPTKmemPool_attribute attr, void * value);
UPTKError UPMemPoolSetAccess(UPTKMemPool_t pool, const UPTKMemAccessDesc * map, size_t count);
UPTKError UPMemPoolGetAccess(UPTKmemAccess_flags * flags, UPTKMemPool_t memPool, UPTKMemLocation * location);
UPTKError UPMemPoolCreate(UPTKMemPool_t * pool, const UPTKMemPoolProps * poolProps);
UPTKError UPMemPoolDestroy(UPTKMemPool_t pool);
UPTKError UPMemAllocFromPoolAsync(UPTKdeviceptr * dptr, size_t bytesize, UPTKMemPool_t pool, UPTKStream_t hStream);
UPTKError UPMemPoolExportToShareableHandle(void * handle_out, UPTKMemPool_t pool, UPTKMemAllocationHandleType handleType, unsigned long long flags);
UPTKError UPMemPoolExportPointer(UPTKMemPoolPtrExportData * shareData_out, UPTKdeviceptr ptr);
UPTKError UPMemPoolImportFromShareableHandle(UPTKMemPool_t * pool_out, void * handle, UPTKMemAllocationHandleType handleType, unsigned long long flags);
UPTKError UPMemPoolImportPointer(UPTKdeviceptr * ptr_out, UPTKMemPool_t pool, UPTKMemPoolPtrExportData * shareData);
UPTKError UPStreamGetCaptureInfo_v2(UPTKStream_t hStream, UPTKStreamCaptureStatus * captureStatus_out, cuuint64_t * id_out, UPTKGraph_t * graph_out, const UPTKGraphNode_t ** dependencies_out, size_t * numDependencies_out);
UPTKError UPStreamUpdateCaptureDependencies(UPTKStream_t hStream, UPTKGraphNode_t * dependencies, size_t numDependencies, unsigned int flags);
UPTKError UPStreamCopyAttributes(UPTKStream_t dst, UPTKStream_t src);
UPTKError UPStreamGetAttribute(UPTKStream_t hStream, UPTKStreamAttrID attr, UPTKStreamAttrValue * value_out);
UPTKError UPStreamSetAttribute(UPTKStream_t hStream, UPTKStreamAttrID attr, const UPTKStreamAttrValue * value);
UPTKError UPEventRecordWithFlags(UPTKEvent_t hEvent, UPTKStream_t hStream, unsigned int flags);
UPTKError UPStreamWaitValue32(UPTKStream_t stream,UPTKdeviceptr addr,cuuint32_t value,unsigned int flags);
UPTKError UPStreamWaitValue64(UPTKStream_t stream,UPTKdeviceptr addr,cuuint64_t value,unsigned int flags);
UPTKError UPFuncGetModule(UPTKmodule * hmod, UPTKfunction hfunc);
UPTKError UPLaunchKernelEx(const UPTKLaunchConfig_t * config, UPTKfunction f, void ** kernelParams, void ** extra);
UPTKError UPGraphAddEventRecordNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, UPTKEvent_t event);
UPTKError UPGraphEventRecordNodeGetEvent(UPTKGraphNode_t hNode, UPTKEvent_t * event_out);
UPTKError UPGraphEventRecordNodeSetEvent(UPTKGraphNode_t hNode, UPTKEvent_t event);
UPTKError UPGraphAddEventWaitNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, UPTKEvent_t event);
UPTKError UPGraphEventWaitNodeGetEvent(UPTKGraphNode_t hNode, UPTKEvent_t * event_out);
UPTKError UPGraphEventWaitNodeSetEvent(UPTKGraphNode_t hNode, UPTKEvent_t event);
UPTKError UPGraphAddExternalSemaphoresSignalNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, const UPTK_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams);
UPTKError UPGraphExternalSemaphoresSignalNodeGetParams(UPTKGraphNode_t hNode, UPTK_EXT_SEM_SIGNAL_NODE_PARAMS * params_out);
UPTKError UPGraphExternalSemaphoresSignalNodeSetParams(UPTKGraphNode_t hNode, const UPTK_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams);
UPTKError UPGraphAddExternalSemaphoresWaitNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, const UPTK_EXT_SEM_WAIT_NODE_PARAMS * nodeParams);
UPTKError UPGraphExternalSemaphoresWaitNodeGetParams(UPTKGraphNode_t hNode, UPTK_EXT_SEM_WAIT_NODE_PARAMS * params_out);
UPTKError UPGraphExternalSemaphoresWaitNodeSetParams(UPTKGraphNode_t hNode, const UPTK_EXT_SEM_WAIT_NODE_PARAMS * nodeParams);
UPTKError UPGraphAddBatchMemOpNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, const UPTK_BATCH_MEM_OP_NODE_PARAMS * nodeParams);
UPTKError UPGraphBatchMemOpNodeGetParams(UPTKGraphNode_t hNode, UPTK_BATCH_MEM_OP_NODE_PARAMS * nodeParams_out);
UPTKError UPGraphBatchMemOpNodeSetParams(UPTKGraphNode_t hNode, const UPTK_BATCH_MEM_OP_NODE_PARAMS * nodeParams);
UPTKError UPGraphExecBatchMemOpNodeSetParams(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, const UPTK_BATCH_MEM_OP_NODE_PARAMS * nodeParams);
UPTKError UPGraphAddMemAllocNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, UPTK_MEM_ALLOC_NODE_PARAMS * nodeParams);
UPTKError UPGraphMemAllocNodeGetParams(UPTKGraphNode_t hNode, UPTK_MEM_ALLOC_NODE_PARAMS * params_out);
UPTKError UPGraphAddMemFreeNode(UPTKGraphNode_t * phGraphNode, UPTKGraph_t hGraph, const UPTKGraphNode_t * dependencies, size_t numDependencies, UPTKdeviceptr dptr);
UPTKError UPGraphMemFreeNodeGetParams(UPTKGraphNode_t hNode, UPTKdeviceptr * dptr_out);
UPTKError UPDeviceGraphMemTrim(UPTKdevice device);
UPTKError UPDeviceGetGraphMemAttribute(UPTKdevice device, UPTKgraphMem_attribute attr, void* value);
UPTKError UPDeviceSetGraphMemAttribute(UPTKdevice device, UPTKgraphMem_attribute attr, void* value);
UPTKError UPGraphInstantiateWithFlags(UPTKGraphExec_t * phGraphExec, UPTKGraph_t hGraph, unsigned long long flags);
UPTKError UPGraphExecEventRecordNodeSetEvent(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, UPTKEvent_t event);
UPTKError UPGraphExecEventWaitNodeSetEvent(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, UPTKEvent_t event);
UPTKError UPGraphExecExternalSemaphoresSignalNodeSetParams(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, const UPTK_EXT_SEM_SIGNAL_NODE_PARAMS * nodeParams);
UPTKError UPGraphExecExternalSemaphoresWaitNodeSetParams(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, const UPTK_EXT_SEM_WAIT_NODE_PARAMS * nodeParams);
UPTKError UPGraphNodeSetEnabled(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, unsigned int isEnabled);
UPTKError UPGraphNodeGetEnabled(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, unsigned int * isEnabled);
UPTKError UPGraphUpload(UPTKGraphExec_t hGraphExec, UPTKStream_t hStream);
UPTKError UPGraphKernelNodeCopyAttributes(UPTKGraphNode_t dst, UPTKGraphNode_t src);
UPTKError UPGraphKernelNodeGetAttribute(UPTKGraphNode_t hNode, UPTKKernelNodeAttrID attr, UPTKKernelNodeAttrValue * value_out);
UPTKError UPGraphKernelNodeSetAttribute(UPTKGraphNode_t hNode, UPTKKernelNodeAttrID attr, const UPTKKernelNodeAttrValue * value);
UPTKError UPGraphDebugDotPrint(UPTKGraph_t hGraph, const char * path, unsigned int flags);
UPTKError UPUserObjectCreate(UPTKUserObject_t * object_out, void * ptr, UPTKhostFn destroy, unsigned int initialRefcount, unsigned int flags);
UPTKError UPUserObjectRetain(UPTKUserObject_t object, unsigned int count);
UPTKError UPUserObjectRelease(UPTKUserObject_t object, unsigned int count);
UPTKError UPGraphRetainUserObject(UPTKGraph_t graph, UPTKUserObject_t object, unsigned int count, unsigned int flags);
UPTKError UPGraphReleaseUserObject(UPTKGraph_t graph, UPTKUserObject_t object, unsigned int count);
UPTKError UPOccupancyAvailableDynamicSMemPerBlock(size_t * dynamicSmemSize, UPTKfunction func, int numBlocks, int blockSize);
UPTKError UPOccupancyMaxPotentialClusterSize(int * clusterSize, UPTKfunction func, const UPTKLaunchConfig_t * config);
UPTKError UPOccupancyMaxActiveClusters(int * numClusters, UPTKfunction func, const UPTKLaunchConfig_t * config);
UPTKError UPDeviceGetUuid_v2(UPTKuuid * uuid, UPTKdevice dev);
UPTKError UPGraphExecChildGraphNodeSetParams(UPTKGraphExec_t hGraphExec, UPTKGraphNode_t hNode, UPTKGraph_t childGraph);
UPTKError UPMemcpyHtoD_v2_ptds(UPTKdeviceptr dstDevice,const void * srcHost,size_t ByteCount);
UPTKError UPMemcpyDtoH_v2_ptds(void * dstHost,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyDtoD_v2_ptds(UPTKdeviceptr dstDevice,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyDtoA_v2_ptds(UPTKarray dstArray,size_t dstOffset,UPTKdeviceptr srcDevice,size_t ByteCount);
UPTKError UPMemcpyAtoD_v2_ptds(UPTKdeviceptr dstDevice,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyHtoA_v2_ptds(UPTKarray dstArray,size_t dstOffset,const void * srcHost,size_t ByteCount);
UPTKError UPMemcpyAtoH_v2_ptds(void * dstHost,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyAtoA_v2_ptds(UPTKarray dstArray,size_t dstOffset,UPTKarray srcArray,size_t srcOffset,size_t ByteCount);
UPTKError UPMemcpyHtoAAsync_v2_ptsz(UPTKarray dstArray,size_t dstOffset,const void * srcHost,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyAtoHAsync_v2_ptsz(void * dstHost,UPTKarray srcArray,size_t srcOffset,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpy2D_v2_ptds(const UPTK_MEMCPY2D * pCopy);
UPTKError UPMemcpy2DUnaligned_v2_ptds(const UPTK_MEMCPY2D * pCopy);
UPTKError UPMemcpy3D_v2_ptds(const UPTK_MEMCPY3D * pCopy);
UPTKError UPMemcpyHtoDAsync_v2_ptsz(UPTKdeviceptr dstDevice,const void * srcHost,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyDtoHAsync_v2_ptsz(void * dstHost,UPTKdeviceptr srcDevice,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyDtoDAsync_v2_ptsz(UPTKdeviceptr dstDevice,UPTKdeviceptr srcDevice,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpy2DAsync_v2_ptsz(const UPTK_MEMCPY2D * pCopy,UPTKStream_t hStream);
UPTKError UPMemcpy3DAsync_v2_ptsz(const UPTK_MEMCPY3D * pCopy,UPTKStream_t hStream);
UPTKError UPMemsetD8_v2_ptds(UPTKdeviceptr dstDevice,unsigned char uc,size_t N);
UPTKError UPMemsetD16_v2_ptds(UPTKdeviceptr dstDevice,unsigned short us,size_t N);
UPTKError UPMemsetD32_v2_ptds(UPTKdeviceptr dstDevice,unsigned int ui,size_t N);
UPTKError UPMemsetD2D8_v2_ptds(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned char uc,size_t Width,size_t Height);
UPTKError UPMemsetD2D16_v2_ptds(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned short us,size_t Width,size_t Height);
UPTKError UPMemsetD2D32_v2_ptds(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned int ui,size_t Width,size_t Height);
UPTKError UPStreamBeginCapture_v2_ptsz(UPTKStream_t hStream,UPTKStreamCaptureMode mode);
UPTKError UPMemcpy_ptds(UPTKdeviceptr dst, UPTKdeviceptr src, size_t ByteCount);
UPTKError UPMemcpyAsync_ptsz(UPTKdeviceptr dst,UPTKdeviceptr src,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpyPeer_ptds(UPTKdeviceptr dstDevice,UPTKcontext dstContext,UPTKdeviceptr srcDevice,UPTKcontext srcContext,size_t ByteCount);
UPTKError UPMemcpyPeerAsync_ptsz(UPTKdeviceptr dstDevice,UPTKcontext dstContext,UPTKdeviceptr srcDevice,UPTKcontext srcContext,size_t ByteCount,UPTKStream_t hStream);
UPTKError UPMemcpy3DPeer_ptds(const UPTK_MEMCPY3D_PEER * pCopy);
UPTKError UPMemcpy3DPeerAsync_ptsz(const UPTK_MEMCPY3D_PEER * pCopy,UPTKStream_t hStream);
UPTKError UPMemPrefetchAsync_ptsz(UPTKdeviceptr devPtr,size_t count,UPTKdevice dstDevice,UPTKStream_t hStream);
UPTKError UPMemsetD8Async_ptsz(UPTKdeviceptr dstDevice,unsigned char uc,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD16Async_ptsz(UPTKdeviceptr dstDevice,unsigned short us,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD32Async_ptsz(UPTKdeviceptr dstDevice,unsigned int ui,size_t N,UPTKStream_t hStream);
UPTKError UPMemsetD2D8Async_ptsz(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned char uc,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPMemsetD2D16Async_ptsz(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned short us,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPMemsetD2D32Async_ptsz(UPTKdeviceptr dstDevice,size_t dstPitch,unsigned int ui,size_t Width,size_t Height,UPTKStream_t hStream);
UPTKError UPStreamGetPriority_ptsz(UPTKStream_t hStream,int * priority);
UPTKError UPStreamGetFlags_ptsz(UPTKStream_t hStream,unsigned int * flags);
UPTKError UPStreamGetCtx_ptsz(UPTKStream_t hStream,UPTKcontext * pctx);
UPTKError UPStreamWaitEvent_ptsz(UPTKStream_t hStream,UPTKEvent_t hEvent,unsigned int Flags);
UPTKError UPStreamEndCapture_ptsz(UPTKStream_t hStream,UPTKGraph_t * phGraph);
UPTKError UPStreamIsCapturing_ptsz(UPTKStream_t hStream,UPTKStreamCaptureStatus * captureStatus);
UPTKError UPStreamGetCaptureInfo_v2_ptsz(UPTKStream_t hStream, UPTKStreamCaptureStatus * captureStatus_out, cuuint64_t * id_out, UPTKGraph_t * graph_out, const UPTKGraphNode_t ** dependencies_out, size_t * numDependencies_out);
UPTKError UPStreamUpdateCaptureDependencies_ptsz(UPTKStream_t hStream, UPTKGraphNode_t * dependencies, size_t numDependencies, unsigned int flags);
UPTKError UPStreamAddCallback_ptsz(UPTKStream_t hStream,UPTKstreamCallback callback,void * userData,unsigned int flags);
UPTKError UPStreamAttachMemAsync_ptsz(UPTKStream_t hStream,UPTKdeviceptr dptr,size_t length,unsigned int flags);
UPTKError UPStreamQuery_ptsz(UPTKStream_t hStream);
UPTKError UPStreamSynchronize_ptsz(UPTKStream_t hStream);
UPTKError UPEventRecord_ptsz(UPTKEvent_t hEvent,UPTKStream_t hStream);
UPTKError UPEventRecordWithFlags_ptsz(UPTKEvent_t hEvent, UPTKStream_t hStream, unsigned int flags);
UPTKError UPLaunchKernel_ptsz(UPTKfunction f,unsigned int gridDimX,unsigned int gridDimY,unsigned int gridDimZ,unsigned int blockDimX,unsigned int blockDimY,unsigned int blockDimZ,unsigned int sharedMemBytes,UPTKStream_t hStream,void ** kernelParams,void ** extra);
UPTKError UPLaunchKernelEx_ptsz(const UPTKLaunchConfig_t * config, UPTKfunction f, void ** kernelParams, void ** extra);
UPTKError UPLaunchHostFunc_ptsz(UPTKStream_t hStream,UPTKhostFn fn,void * userData);
UPTKError UPGraphicsMapResources_ptsz(unsigned int count,UPTKGraphicsResource_t * resources,UPTKStream_t hStream);
UPTKError UPGraphicsUnmapResources_ptsz(unsigned int count,UPTKGraphicsResource_t * resources,UPTKStream_t hStream);
UPTKError UPStreamWriteValue32_v2_ptsz(UPTKStream_t stream, UPTKdeviceptr addr, cuuint32_t value, unsigned int flags);
UPTKError UPStreamWaitValue32_v2_ptsz(UPTKStream_t stream, UPTKdeviceptr addr, cuuint32_t value, unsigned int flags);
UPTKError UPStreamWriteValue64_v2_ptsz(UPTKStream_t stream, UPTKdeviceptr addr, cuuint64_t value, unsigned int flags);
UPTKError UPStreamWaitValue64_v2_ptsz(UPTKStream_t stream, UPTKdeviceptr addr, cuuint64_t value, unsigned int flags);
UPTKError UPStreamBatchMemOp_v2_ptsz(UPTKStream_t stream, unsigned int count, UPTKstreamBatchMemOpParams * paramArray, unsigned int flags);
UPTKError UPLaunchCooperativeKernel_ptsz(UPTKfunction f,unsigned int gridDimX,unsigned int gridDimY,unsigned int gridDimZ,unsigned int blockDimX,unsigned int blockDimY,unsigned int blockDimZ,unsigned int sharedMemBytes,UPTKStream_t hStream,void ** kernelParams);
UPTKError UPSignalExternalSemaphoresAsync_ptsz(const UPTKExternalSemaphore_t * extSemArray,const UPTK_EXTERNAL_SEMAPHORE_SIGNAL_PARAMS * paramsArray,unsigned int numExtSems,UPTKStream_t stream);
UPTKError UPWaitExternalSemaphoresAsync_ptsz(const UPTKExternalSemaphore_t * extSemArray,const UPTK_EXTERNAL_SEMAPHORE_WAIT_PARAMS * paramsArray,unsigned int numExtSems,UPTKStream_t stream);
UPTKError UPGraphUpload_ptsz(UPTKGraphExec_t hGraphExec, UPTKStream_t hStream);
UPTKError UPGraphLaunch_ptsz(UPTKGraphExec_t hGraphExec,UPTKStream_t hStream);
UPTKError UPStreamCopyAttributes_ptsz(UPTKStream_t dst, UPTKStream_t src);
UPTKError UPStreamGetAttribute_ptsz(UPTKStream_t hStream, UPTKStreamAttrID attr, UPTKStreamAttrValue * value_out);
UPTKError UPStreamSetAttribute_ptsz(UPTKStream_t hStream, UPTKStreamAttrID attr, const UPTKStreamAttrValue * value);
UPTKError UPMemMapArrayAsync_ptsz(UPTKarrayMapInfo * mapInfoList, unsigned int count, UPTKStream_t hStream);
UPTKError UPMemFreeAsync_ptsz(UPTKdeviceptr dptr, UPTKStream_t hStream);
UPTKError UPMemAllocAsync_ptsz(UPTKdeviceptr * dptr, size_t bytesize, UPTKStream_t hStream);
UPTKError UPMemAllocFromPoolAsync_ptsz(UPTKdeviceptr * dptr, size_t bytesize, UPTKMemPool_t pool, UPTKStream_t hStream);

#ifdef __cplusplus
}
#endif

