message(STATUS "include error test case")
set(RUNTIME_ERROR_DIR ${CMAKE_CURRENT_SOURCE_DIR}/runtime/error)

set(RUNTIME_ERROR_DEVICE_DIR ${RUNTIME_ERROR_DIR}/device)
set(RUNTIME_ERROR_EVENT_DIR ${RUNTIME_ERROR_DIR}/event)


set(RUNTIME_ERROR_DEVICE_TEST_FILES
    ${RUNTIME_ERROR_DEVICE_DIR}/testdir.cu
    ${RUNTIME_ERROR_DEVICE_TEST_TMP_FILES}

)
set(RUNTIME_ERROR_EVENT_TEST_FILES
    ${RUNTIME_ERROR_EVENT_DIR}/testdir2.cu
    ${RUNTIME_ERROR_EVENT_TEST_TMP_FILES}
)

set(RUNTIME_ERROR_TEST_FILES
    ${RUNTIME_ERROR_DIR}/cudaGetErrorNameTest.cu
    ${RUNTIME_ERROR_DIR}/cudaGetErrorStringTest.cu
    ${RUNTIME_ERROR_DIR}/cudaGetLastErrorTest.cu
    ${RUNTIME_ERROR_DIR}/cudaPeekAtLastErrorTest.cu
    ${RUNTIME_ERROR_TEST_TMP_FILES}
    ${RUNTIME_ERROR_DEVICE_TEST_FILES}
    ${RUNTIME_ERROR_EVENT_TEST_FILES}
)
