message(STATUS "include pin_H2D test case")
set(PERFORMANCE_HIPMALLOC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/performance/hipmalloc_performance)

set(PERFORMANCE_HIPMALLOC_TEST_FILES 
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_1.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_2.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_3.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_4.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_5.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_6.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_7.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_8.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_9.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_10.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_11.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_12.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_13.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_14.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_15.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_16.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_17.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_18.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_19.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_20.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_21.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_22.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_23.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_24.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_25.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_26.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_27.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_28.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_29.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_30.cpp
  ${PERFORMANCE_HIPMALLOC_DIR}/hipmalloc_31.cpp
)