message(STATUS include cufft_runable test case)
set(CUFFT_RUNABLE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cufft_runable)

set(CUFFT_RUNABLE_TEST_FILES
    ${CUFFT_RUNABLE_DIR}/c2c_1d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_1d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_1d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_1d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_2d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_2d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_2d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_2d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_3d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_3d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_3d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/c2c_3d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_1d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_1d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_2d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_2d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_3d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/c2c_many_3d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_1d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_1d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_1d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_1d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_2d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_2d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_2d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_2d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_3d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_3d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_3d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_3d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_1d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_1d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_2d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_2d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_3d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/d2zz2d_many_3d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_1d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_1d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_1d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_1d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_2d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_2d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_2d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_2d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_3d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_3d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_3d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_3d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_1d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_1d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_2d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_2d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_3d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/r2cc2r_many_3d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_1d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_1d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_1d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_1d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_2d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_2d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_2d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_2d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_3d_inplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_3d_inplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_3d_outofplace.cu
    ${CUFFT_RUNABLE_DIR}/z2z_3d_outofplace_make_plan.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_1d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_1d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_2d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_2d_outofplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_3d_inplace_basic.cu
    ${CUFFT_RUNABLE_DIR}/z2z_many_3d_outofplace_basic.cu

    ${CUFFT_RUNABLE_TEST_TMP_FILES}
    )


