message(STATUS "include hipMemset test case")
set(PERFORMANCE_HIPMEMSET_DIR ${CMAKE_CURRENT_SOURCE_DIR}/performance/hipmemset_performance)

set(PERFORMANCE_HIPMEMSET_TEST_FILES
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_1.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_2.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_3.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_4.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_5.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_6.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_7.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_8.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_9.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_10.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_11.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_12.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_13.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_14.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_15.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_16.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_17.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_18.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_19.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_20.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_21.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_22.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_23.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_24.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_25.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_26.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_27.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_28.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_29.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_30.cpp
  ${PERFORMANCE_HIPMEMSET_DIR}/hipMemset_31.cpp
)