message(STATUS "include pin_D2H test case")
set(PERFORMANCE_PIN_D2H_DIR ${CMAKE_CURRENT_SOURCE_DIR}/performance/pin_D2H)

set(PERFORMANCE_PIN_D2H_TEST_FILES 
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_1.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_2.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_3.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_4.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_5.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_6.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_7.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_8.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_9.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_10.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_11.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_12.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_13.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_14.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_15.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_16.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_17.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_18.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_19.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_20.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_21.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_22.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_23.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_24.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_25.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_26.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_27.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_28.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_29.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_30.cpp
	${PERFORMANCE_PIN_D2H_DIR}/pin_D2H_31.cpp
	)
