message(STATUS "include pin_H2D test case")
set(PERFORMANCE_PIN_H2D_DIR ${CMAKE_CURRENT_SOURCE_DIR}/performance/pin_H2D)

set(PERFORMANCE_PIN_H2D_TEST_FILES 
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_1.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_2.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_3.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_4.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_5.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_6.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_7.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_8.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_9.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_10.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_11.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_12.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_13.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_14.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_15.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_16.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_17.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_18.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_19.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_20.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_21.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_22.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_23.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_24.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_25.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_26.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_27.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_28.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_29.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_30.cpp
	${PERFORMANCE_PIN_H2D_DIR}/pin_H2D_31.cpp
	)
