message(STATUS "include memory test case")
set(RUNTIME_MEMORY_DIR ${CMAKE_CURRENT_SOURCE_DIR}/runtime/memory)

set(RUNTIME_MEMORY_TEST_FILES
        ${RUNTIME_MEMORY_DIR}/cudaHostGetFlagsTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostGetFlagsTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostGetFlagsTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostRegisterTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostRegisterTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostRegisterTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaHostRegisterTest4.cu
        #${RUNTIME_MEMORY_DIR}/cudaMalloc3DArrayTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaMallocArrayTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocHostTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocHostTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocHostTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocManagedTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocPitchTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocPitchTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest4.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest5.cu
        ${RUNTIME_MEMORY_DIR}/cudaMallocTest6.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemGetInfoTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpy2DAsyncTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpy2DAsyncTest_2.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpy2DTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpy2DTest2.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpy2DTest_2.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpy2DToArrayTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpy3DTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest1.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest2.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest4.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest5.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest6.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest7.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest8.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyAsyncTest9.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest3.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest4.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest5.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest6.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemcpyTest7.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemcpyToArrayTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemset2DTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemsetAsyncTest.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemsetD8Test.cu
        ${RUNTIME_MEMORY_DIR}/cudaMemsetTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemsetTest1.cu
        #${RUNTIME_MEMORY_DIR}/cudaMemsetTest2.cu
        ${RUNTIME_MEMORY_DIR}/cudaPerformanceUnpinD2H_default.cu
        ${RUNTIME_MEMORY_DIR}/cudaPerformanceUnpinD2H_default_1.cu
        #${RUNTIME_MEMORY_DIR}/cudaPointerGetAttributesTest.cu
        #${RUNTIME_MEMORY_DIR}/cudaPointerGetAttributesTest2.cu
)
